apiVersion: v1
kind: Service
metadata:
  name: library
  labels:
    app.kubernetes.io/name: library
spec:
  selector:
    app.kubernetes.io/name: library
  ports:
    - name: http
      port: 80
      targetPort: http
