apiVersion: v1
kind: Service
metadata:
  name: assistant
  labels:
    app.kubernetes.io/name: assistant
spec:
  selector:
    app.kubernetes.io/name: assistant
  ports:
    - name: http
      port: 80
      targetPort: http
