#!/usr/bin/env python3
"""The assistant's alerts live in its repository (observability/alerts.yaml),
where they are unit-tested. This cluster runs them as a PrometheusRule.

  python3 scripts/alerts_mirror.py           write apps/base/assistant/prometheusrule.yaml
  python3 scripts/alerts_mirror.py --check   fail if it differs from the source
"""

import sys
import urllib.request
from pathlib import Path

import yaml

SOURCE = "https://raw.githubusercontent.com/hasanozkan/llm-tool-calling-assistant/main/observability/alerts.yaml"
TARGET = Path(__file__).resolve().parent.parent / "apps" / "base" / "assistant" / "prometheusrule.yaml"
HEADER = (
    "# GENERATED by scripts/alerts_mirror.py from the assistant's observability/alerts.yaml,\n"
    "# where these rules are unit-tested. Change them there; CI fails if this copy drifts.\n"
)


def render(source: str) -> str:
    groups = yaml.safe_load(source)["groups"]
    rule = {
        "apiVersion": "monitoring.coreos.com/v1",
        "kind": "PrometheusRule",
        "metadata": {"name": "assistant"},
        "spec": {"groups": groups},
    }
    return HEADER + yaml.safe_dump(rule, sort_keys=False, width=120)


def main() -> int:
    source = urllib.request.urlopen(SOURCE, timeout=30).read().decode()  # noqa: S310 — fixed https URL
    wanted = render(source)
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text() != wanted:
            print("apps/base/assistant/prometheusrule.yaml is stale: run scripts/alerts_mirror.py and commit.")
            return 1
        print("alerts mirror: ok")
        return 0
    TARGET.write_text(wanted)
    print(f"wrote {TARGET.relative_to(Path.cwd()) if TARGET.is_relative_to(Path.cwd()) else TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
